### PR TITLE
Fix error handling for TDML inputs

### LINKED ISSUE #1349: TDML Execute doesn't work when fields are missing from launch config
Once the description is removed, there are three fields in the tdmlConfig (action, path, and name). Action will always be required. If path is missing, the user should be prompted for the tdml file. If name is missing, we should take the path from the config, extract the names from that TDML file and prompt the user for which name to use.

### PR DESCRIPTION
**Pull request by michael-hoke**
Closes #1349

### CODE REVIEW

File: src/adapter/activateDaffodilDebug.ts [hunk 1]
```diff
@@ -175,17 +175,6 @@ async function createDebugRunFileConfigs(
...
-          tdmlConfig.name =
-            tdmlConfig.name ||
-            (await vscode.commands.executeCommand(
-              'extension.dfdl-debug.getTDMLName',
-              tdmlConfig.path
-            ))
-
-          if (!tdmlConfig.name) {
-            return
-          }
```
Comment (shanedell) [inline src/adapter/activateDaffodilDebug.ts:188]: Why was this code block removed?

**Review by rthomas320 — APPROVED** [review]
Tested on Windows 10. Works as expected.
+1

**Review by shanedell — APPROVED** [review]
+1
