### PR TITLE
Search Scrolling Index Lag Fixed

### LINKED ISSUE #584: Search Prev/Next buttons not properly sync'ed with the Offset
Open this repo's `package.json`, then `Search` for `Apache`, click the `Prev` and `Next` buttons and observe what's being scrolled to and what's being displayed in the `Offset` input box and see that they aren't matching up correctly.

### PR DESCRIPTION
**Pull request by stricklandrbls**
- Too much offset input manipulation was happening with too many different variables before actually going to an offset. This has been reduced to modular arithmetic on the `searchIndex`

Closes #584

### CODE REVIEW

File: src/svelte/src/components/dataEditor.svelte [hunk 1]
```diff
@@ -229,32 +229,13 @@ limitations under the License.
...
-      $gotoOffsetInput = $searchResults[index].toString($addressValue)
-      goTo($gotoOffset)
-    }
-  }
-
-  function scrollSearchNext() {
-    scrollSearchResults(true)
-  }
+  function updateSearchResults(offset?: number) {
+    $searchIndex = !offset
```
Comment (scholarsmate) [inline src/svelte/src/components/dataEditor.svelte:233]: Why bother making the offset optional then blindly force it?

**Review by scholarsmate — APPROVED** [review]
+1, 👍

I like the simplification, fixing the offset issue.

**Review by Shanedell — APPROVED** [review]
+1 👍
