### PR TITLE
Omega Edit status messages must be in tolerance

### LINKED ISSUE #989: CPU Load Average reports -1.0.0 in WIndows
In Windows, hover over the green dot and see that the CPUI Load Average is -1.00, which is incorrect.  It may not be getting reported properly by the server or may not be available from the JVM in Windows.

If the CPU Load Average is not easily found for Windows, instead of showing -1.00, we should not report it at all.

### PR DESCRIPTION
**Pull request by scholarsmate**
To test this, run the Data Editor from a Windows machine, hover over the green dot down where the Omega Edit status information is, and check that the CPU Load Average is now not being reported because it is not in tolerance.

Fixes CPU Load Average reports -1.0.0 in Windows.

closes #989

### CODE REVIEW

**Comment by stricklandrbls** [comment]
>  check that the CPU Load Average is now no being reported because it is not in tolerance.

Is that supposed to say "_not_ being reported"? Running this PR as described but I don't see the `CPULoadAverage` from this section:
https://github.com/apache/daffodil-vscode/blob/4b09ed25b80d6c9f7cd1a811c0aa68871e1b6407/src/svelte/src/components/ServerMetrics/ServerMetrics.svelte#L133-L136

**Screenshot Reference**
image

**Review by rthomas320 — COMMENTED** [review]
This change seems to have broken the "none" "action" option for tdml configuration.
image
If I change the tdml "action" to "generate" the selected documents and the dataEditor open. when I hover over the green dot, the CPU load average is not present.
image

**Comment by scholarsmate** [comment]
@stricklandrbls, that is the expected behavior.  If a measurement is not in tolerance, it doesn't get reported at all.  Not sure why the Windows JVM can't properly report the average CPU load, but if that ever does get repaired, then it will be properly reported in the metrics at that time without any changes to this code.

@rthomas320, perhaps that's happening because this branch needs to be rebased to incorporate any recent updates and fixes.  If that's the case, I'll do a rebase and force push it.

**Comment by scholarsmate** [comment]
@rthomas320, the branch is currently up-to-date with main.  Can you please try again?  Be sure to run `git clean -fdx` before the build to make sure it's clean.

**Comment by stricklandrbls** [comment]
@scholarsmate 
I retested the PR with the main rebase and it still works as expected.

--- 
> ... If a measurement is not in tolerance, it doesn't get reported at all ...

I'm wondering if we should have a placeholder for this in the output instead of just omitting it entirely.

File: src/svelte/src/components/ServerMetrics/ServerMetrics.svelte [hunk 1]
```diff
@@ -107,32 +107,49 @@ limitations under the License.
...
+        {/if}
+        {#if heartbeat.serverUptime > 0}
+          <b>Uptime:</b>
+          {prettyPrintUptime(heartbeat.serverUptime)}
+        {/if}
+        {#if heartbeat.sessionCount > 0}
+          <b>Session Count:</b>
+          {heartbeat.sessionCount},
+        {/if}
+        {#if heartbeat.serverCpuLoadAverage > 0}
```
Comment (hdalsania) [inline src/svelte/src/components/ServerMetrics/ServerMetrics.svelte:133]: Because of this change, windows does not display CPU Load Avg. at all because it is not >0? 

Windows:
image


Linux:
image

Comment (scholarsmate) [reply src/svelte/src/components/ServerMetrics/ServerMetrics.svelte:133]: Correct, you and @stricklandrbls said the same.  I wanted to avoid placeholders simply due to (lack of) real estate.

Comment (stricklandrbls) [reply src/svelte/src/components/ServerMetrics/ServerMetrics.svelte:133]: > I wanted to avoid placeholders simply due to (lack of) real estate.

The using `humanReadableByteLength(byteLength: number): string ` from `./src/svelte/src/utilities/display.ts` on the "Memory Usage" value might help with the real estate. I'm be fine approving this PR with omitting the `CPULoadAverage` value for Windows and possibly creating another ticket for restructuring the way server information is output.

**Review by stricklandrbls — APPROVED** [review]
+1

Though we should look into restructuring the server info output method.

**Review by rthomas320 — APPROVED** [review]
Works with TDML action set to none and CPU load average is not showing in the hover over status green dot.
