### PR TITLE
fix save over original file (fixes #501)

### LINKED ISSUE #501: Save is not overwriting the original file
When attempting to save over the file being edited, nothing happens.

### PR DESCRIPTION
**Pull request by scholarsmate**
fixes #501

### CODE REVIEW

File: src/omega_edit/dataEditWebView.ts [hunk 1]
```diff
@@ -334,25 +304,17 @@ export class DataEditWebView implements vscode.Disposable {
           })
           .then(async (uri) => {
             if (uri && uri.fsPath) {
-              if (uri.path === this.fileToEdit) {
-                await this.saveSession(this.omegaSessionId, true).catch(() => {
-                  vscode.window.showErrorMessage('Failed to save')
+              await omegaEditSession
+                .saveSession(this.omegaSessionId, uri.path, true)
+                .then(async (fp) => {
+                  vscode.window.showInformationMessage(`Saved to file: ${fp}`)
```
Comment (arosien) [inline src/omega_edit/dataEditWebView.ts:310]: Concern: I'll need to load this in a real editor, but I'm not sure `saveSession` returns the file path.

Comment (scholarsmate) [reply src/omega_edit/dataEditWebView.ts:310]: It does.  It has to, because if you set overwrite to `false`, and give it a file path that exists, a new file path will be generated in Ωedit and returned.  You can search for `save` in the C API documentation for more (see: https://ctc-oss.github.io/omega-edit/index.html).  Also testing shows this is the case.

**Comment by Shanedell** [comment]
@scholarsmate Is there supposed to be a `Save As` or something similar added? This seems like it will always overwrite the file so what if we want to make a new one? Or do you plan that being a separate PR?

**Comment by scholarsmate** [comment]
@Shanedell, the `Save` button opens a file picker that allows you to save the session any way you please.  It can be saved over the file being edited, to a new file, or overwrite some other existing file.

**Review by Shanedell — APPROVED** [review]
+1 👍

**Comment by scholarsmate** [comment]
@arosien, what else are you waiting on?

File: src/omega_edit/dataEditWebView.ts (hunk 1 above)
Comment (arosien) [reply src/omega_edit/dataEditWebView.ts:310]: Sorry, bad code navigation in Github.

**Review by arosien — APPROVED** [review]
:+1:
