### PR TITLE
fixes an issue where the incorrect nsprefix was applied to dfdl element

### LINKED ISSUE #1221: IntelliSense: Discrepancy Between Dropdown Items' Namespace and Inserted Items' Namespace
### Description

Version: 1.4.1 Snapshot

For inserting elements, IntelliSense suggests elements with the `dfdl:` prefix as shown below: 

Image

however, upon going through with the suggestion, it inserts the element with the `xs:` prefix instead. 

Image

It seems to be doing this for other suggestions too

Image

#### In [helloWorldPlusLongForm.dfdl.xsd](https://github.com/apache/daffodil-vscode/blob/main/src/tests/data/helloWorldPlusLongForm.dfdl.xsd)
1. Download https://github.com/apache/daffodil-vscode/blob/main/src/tests/data/helloWorldPlusLongForm.dfdl.xsd
2. Open up helloWorldPlusLongForm.dfdl.xsd in VSCode
3. Navigate to line 33, col 1

Image

4. Press `CTRL` + `space`
5. Suggestions should look like the following

Image

6. Proceed with any of the suggestions and observe how they all have the `xs` namespace instead of the `dfdl` namespace as the suggestions list. 
7. Place cursor at line 68 column 59, after >

Image

8. Press `Ctrl` + `Space`

Image

9. insert any of the suggestions listed in the screenshot. Most of the suggestions are inconsistent with the suggestion. 

### Fix Idea

Determine list of elements common in [dfdl](https://daffodil.apache.org/docs/dfdl/#_Toc62570080) and [xsd schemas](https://www.w3.org/2001/XMLSchema)

For the list of elements common in the two schemas, have a dfdl: and a xs: option appear. 

#### List of Elements only in DFDL (in progress) 

- dfdl:assert
- dfdl:defineVariable
- dfdl:discriminator

### PR DESCRIPTION
**Pull request by rthomas320**
Fixes an issue where the incorrect nsprefix was applied to dfdl element tags

Closes #1221

Testing instructions are here: https://github.com/apache/daffodil-vscode/issues/1221

### CODE REVIEW

**Review by JeremyYao — APPROVED** [review]
See later review

File: src/language/providers/intellisense/elementItems.ts [hunk 1]
```diff
@@ -49,17 +49,17 @@ export const elementCompletion = (definedVariables, nsPrefix) => {
       },
       {
         item: 'dfdl:assert',
-        snippetString: '<' + nsPrefix + 'assert $0',
+        snippetString: '<' + 'dfdl:' + 'assert $0',
```
Comment (scholarsmate) [inline src/language/providers/intellisense/elementItems.ts:52]: I see no advantage to gluing together these static strings.

`snippetString: '<' + 'dfdl:' + 'assert $0',`

Should be simply:

`snippetString: '<dfdl:assert $0',`

**Review by scholarsmate — CHANGES_REQUESTED** [review]
Don't glue together static strings unless there is a compelling reason to do so, and if so, please put a comment in the code explaining why.

**Review by JeremyYao — CHANGES_REQUESTED** [review]
My previous review was a bit hastily done. Are you able to create a consts file? Something that looks like https://github.com/ctc-oss/daffodil-vscode/commit/9fde0695e2a4ddc10f4ed0fade1e11b69ce23ffe?

File: src/language/providers/intellisense/elementItems.ts (hunk 1 above)
Comment (rthomas320) [reply src/language/providers/intellisense/elementItems.ts]: agreed

**Comment by rthomas320** [comment]
Testing instructions are here: https://github.com/apache/daffodil-vscode/issues/1221

File: src/language/providers/intellisense/elementItems.ts [hunk 2]
```diff
@@ -49,17 +49,17 @@ export const elementCompletion = (definedVariables, nsPrefix) => {
       },
       {
         item: 'dfdl:assert',
-        snippetString: '<' + nsPrefix + 'assert $0',
+        snippetString: '<' + 'dfdl:assert $0',
```
Comment (scholarsmate) [inline src/language/providers/intellisense/elementItems.ts:52]: Change these from something like this:
 `snippetString: '<' + 'dfdl:assert $0',`
 To something like this:
 `snippetString: '<dfdl:assert $0',`

**Review by scholarsmate — APPROVED** [review]
+1, thank you.

**Review by scholarsmate — APPROVED** [review]
+1

File: src/language/providers/intellisense/elementItems.ts [hunk 3]
```diff
@@ -49,17 +49,17 @@ export const elementCompletion = (definedVariables, nsPrefix) => {
       },
       {
         item: 'dfdl:assert',
-        snippetString: '<' + nsPrefix + 'assert $0',
+        snippetString: '<dfdl::assert $0',
```
Comment (shanedell) [inline src/language/providers/intellisense/elementItems.ts:52]: @rthomas320 Is this line, line 57 and line 58 supposed to `dfdl:` instead of `dfdl::`?

**Review by shanedell — APPROVED** [review]
+1
