### PR TITLE
Launch wizard updates and rename data editor vars

### LINKED ISSUE #617: Add Ωedit server port setting to the launch wizard
The Ωedit server port is not currently configurable in the launch setting wizard, but should be.

### LINKED ISSUE #619: Launch Wizard Broken
Looks like with some of the updates for TDML configs the launch wizard was broken. Some of the styling also does not match up.

### LINKED ISSUE #621: Rename dataEditor.* config variables
To be consistent the `dataEditor.*` variables should be renamed.

eg

```json
{
    "dataEditor.omegaEditPort": 9000
    "dataEditor.logFile": "${workspaceFolder}/dataEditor-${omegaEditPort}.log",
    "dataEditor.logLevel": "info"
}
```

should become something like

```json
{
    "dataEditor": {
        "omegaEditPort": 9000
        "logFile": "${workspaceFolder}/dataEditor-${omegaEditPort}.log",
        "logLevel": "info"
    }
}
```

### PR DESCRIPTION
**Pull request by Shanedell**
Launch wizard updates and rename data editor vars:

- Rename variables dataEditor.* to be under an object called dataEditorConfig.
  - The variables that can be inside of that object are omegaEditPort, logFile and logLevel
- Add missing config keys and values to parsed configs.
  - If not done this causes the launch wizard to not open.
- Fix a issue with some TDML settings not showing up properly.
- Update TDML config settings styling to better match the rest of the launch wizard.
  - When these items are hidden, the height and width are set to 0 so no large black space would be created in the UI.
- Add support for setting data editor settings. These were omegaEditPort, logFile and logLevel.
- Don't show TDML name field when action is set to "none".

Closes #617
Closes #619
Closes #621

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -147,6 +150,15 @@ export function getConfig(
     daffodilDebugClasspath: daffodilDebugClasspath
       ? daffodilDebugClasspath
       : defaultConf.get('daffodilDebugClasspath', ''),
+    dataEditorOmegaEditPort: dataEditorOmegaEditPort
+      ? dataEditorOmegaEditPort
+      : defaultConf.get('dataEditor.omegaEditPort', 9000),
```
Comment (scholarsmate) [inline src/utils.ts:155]: Can't we pull the default port from package.json?

Comment (Shanedell) [reply src/utils.ts:155]: That is what this trying to do. The second value is the default value if nothing is found

File: package.json [hunk 2]
```diff
@@ -627,17 +618,17 @@
             },
             "default": {}
           },
-          "dataEditor.omegaEditPort": {
+          "dataEditorOmegaEditPort": {
```
Comment (scholarsmate) [inline package.json:621]: Should this just be `omegaEditPort`?

File: package.json [hunk 3]
```diff
@@ -627,17 +618,17 @@
...
             "type": "integer",
             "description": "Editor server default port",
             "default": 9000
           },
-          "dataEditor.logFile": {
+          "dataEditorLogFile": {
```
Comment (scholarsmate) [inline package.json:626]: Should this just be `logFile`?

File: package.json [hunk 4]
```diff
@@ -627,17 +618,17 @@
...
             "type": "string",
             "description": "Path to log file for data editor",
             "default": "${workspaceFolder}/dataEditor-${omegaEditPort}.log"
           },
-          "dataEditor.logLevel": {
+          "dataEditorLogLevel": {
```
Comment (scholarsmate) [inline package.json:631]: Should this just be `logLevel`?

File: package.json (hunk 2 above)
Comment (Shanedell) [reply package.json:621]: I believe they should all keep `dataEditor` so we are aware of what they are for. These ones are used for getting default values.

File: src/utils.ts (hunk 1 above)
Comment (scholarsmate) [reply src/utils.ts]: Shouldn't something _always_ be specified for a default server port (debug, data, or otherwise) in `package.json`.  If not, that's a bug in my opinion and the code should error out indicating that no default value was specified in `package.json` when it should have been.

Comment (scholarsmate) [reply src/utils.ts]: Sometimes you want a failsafe (e.g., PID files to help recover from an unexpected crash), and other times you want to _reveal_ programming errors (e.g., asserts).  In this case, I'd prefer the latter.

Comment (Shanedell) [reply src/utils.ts]: I can see where you are coming from. But I believe maybe we should ask others for their input as well before deciding what to change to and do from now on. @stevedlawrence @mbeckerle @rt320 @arosien @stricklandrbls @michael-hoke @NolanMatt @nlewis05  what are your thoughts?

Comment (stevedlawrence) [reply src/utils.ts]: I don't think I have a strong opinion one way or the other in general--there's good arguments for both sides. It's probably easier to detect typos or configuration name changes if you don't do defaults, so I'd maybe lean towards no default.

That said, in this particular case it looks like all uses of `defaultConf.get(...)` provide a default value, so at least in this PR I suggest we stay consistent with that and provide a default value.

**Comment by scholarsmate** [comment]
@Shanedell, make sure to also document the changes here https://github.com/apache/daffodil-vscode/wiki/Apache-Daffodil™-Extension-for-Visual-Studio-Code:-v1.3.0.

**Review by scholarsmate — APPROVED** [review]
+1, 👍

File: package.json [hunk 5]
```diff
@@ -413,27 +413,14 @@
...
-                "description": "Log level for data editor",
-                "enum": [
-                  "error",
-                  "warn",
-                  "info",
-                  "debug",
-                  "trace"
-                ],
-                "default": "info"
+              "dataEditorConfig": {
```
Comment (arosien) [inline package.json:416]:
```suggestion
              "dataEditor": {
```
`Config` seems redundant.

File: package.json [hunk 6]
```diff
@@ -413,27 +413,14 @@
...
+                "type": "object",
+                "description": "Configuration for Data Editor. Settings are omegaEditPort, logFile and logLevel",
+                "default": {
+                  "omegaEditPort": 9000,
```
Comment (arosien) [inline package.json:420]:
```suggestion
                  "port": 9000,
```
Maybe just `port`?

File: package.json (hunk 2 above)
Comment (arosien) [inline package.json:621]: I'm unsure what the schema definitions in this `configuration` section are for. They aren't official sections listed under https://code.visualstudio.com/api/extension-guides/debugger-extension#anatomy-of-the-package.json-of-a-debugger-extension. 

Looking around, it seems to be a custom configuration section we use to provide default values(?). If so, it can probably be removed and the `contributes/debuggers/configurationAttributes` section can be the sole location of launch schema and defaults.

This should probably be a different ticket for a different release.

File: package.json (hunk 6 above)
Comment (scholarsmate) [reply package.json:420]: Since it's namespaced, I think just `port` is a fine choice.

File: package.json (hunk 5 above)
Comment (scholarsmate) [reply package.json:416]: Agreed.

Comment (Shanedell) [reply package.json:416]: @arosien Should this be changed everywhere `dataEditorConfig` is used or just inside of package.json? Meaning like the interface that was created, etc.

File: package.json (hunk 2 above)
Comment (Shanedell) [reply package.json:621]: Yeah this what it is for. However, it was separated from `configurationAttributes` as we were using it for defaults and making sure the type is right initially. I don't think we want to move them into `configurationAttributes`, doing this allows the user to change their values, but they are only there for initial values of object attributes. I think we actually wouldn't want the user to have the ability to set these item, at least some of them since it really wouldn't do anything.

File: package.json (hunk 5 above)
Comment (Shanedell) [reply package.json]: I just renamed the package.json settings. So that in TS code you still know its a dataEditorConfig not the actual dataEditor.

**Review by arosien — APPROVED** [review]
👍 code looks good, haven't tried it out though
