### PR TITLE
Set debugServer to 4711 (default) if not specified in config.

### LINKED ISSUE #494: Extension doesn't connect to launched backend if debugServer launch property missing
If you don't include `"debugServer": 4711` in the `launch.json` config then the debug session doesn't connect to the launched debugger backend (which is listening on 4711, btw), and the backend stops itself after the default timeout of 10s is reached.

I'm not sure what the extension is getting stuck on when this situation happens. But it sounds like some default value isn't filled in, or the missing case is being handled incorrectly.

### PR DESCRIPTION
**Pull request by shanedell**
Set debugServer to 4711 (default) if not specified in config.

Closes #494

### CODE REVIEW

**Review by scholarsmate — APPROVED** [review]
+1, LGTM.

**Comment by arosien** [comment]
I think this is a regression from https://github.com/apache/daffodil-vscode/pull/453. Tracing it...

File: src/adapter/activateDaffodilDebug.ts [hunk 1]
```diff
@@ -406,6 +406,10 @@ class DaffodilConfigurationProvider
       config = getConfig('Launch', 'launch', 'dfdl')
     }
 
+    if (!config.debugServer) {
```
Comment (arosien) [inline src/adapter/activateDaffodilDebug.ts:409]: I need to try this, as this doesn't look like it will do anything given code like 

https://github.com/apache/daffodil-vscode/blob/main/src/daffodilDebugger.ts#LL211-L215

which doesn't even use the `serverPort`.

Comment (arosien) [reply src/adapter/activateDaffodilDebug.ts:409]: Ah ok, it's returning the (modified) config to the VS Code debug system, which uses the info to find the launched debug port. So if the `serverPort` is undefined, that system doesn't know to connect to some port.

**Review by arosien — APPROVED** [review]
👍

File: src/adapter/activateDaffodilDebug.ts (hunk 1 above)
Comment (Shanedell) [reply src/adapter/activateDaffodilDebug.ts:409]: Yeah that will need update will make an issue
