### PR TITLE
Fix java command line arguments for Java 17+

### LINKED ISSUE #895: Java 17 fix doesn't work correctly on Windows
daffodil-debugger.bat, created from bat-template does not correctly parse the extra args required for java 17 and above.

['-J--add-opens', '-J**java.base/java.lang=ALL-UNNAMED**']

The second parameter is being terminated at the period after the first "java"
Thus, the issued java command is malformed:

"java"   --add-opens **java**  -cp ""C:\\...\daffodil-vscode\daffodil-debugger-3.5.0-1.3.1\bin\\\..\lib\\org.apache.daffodil.daffodil-debugger-1.3.1-classpath.jar"" org.apache.daffodil.debugger.dap.DAPodil  --listenPort 4711 **.base/java.lang ALL-UNNAMED**

### PR DESCRIPTION
**Pull request by lrbarber**
Close #895 
Changed assignment of extraArgs in utils.ts to be **os** specific and fix Java 17+ on Windows

### CODE REVIEW

File: src/daffodilDebugger/utils.ts [hunk 1]
```diff
@@ -43,8 +43,9 @@ export const shellArgs = (port: number, isAtLeastJdk17: boolean) => {
   // Workaround: certain reflection (used by JAXB) isn't allowed by default in JDK 17:
   //   https://docs.oracle.com/en/java/javase/17/migrate/migrating-jdk-8-later-jdk-releases.html#GUID-7BB28E4D-99B3-4078-BDC4-FC24180CE82B
   const extraArgs = isAtLeastJdk17
-    ? ['-J--add-opens', '-Jjava.base/java.lang=ALL-UNNAMED']
-    : []
+  ? osCheck( ['-J"--add-opens java.base/java.lang=ALL-UNNAMED"'],
```
Comment (shanedell) [inline src/daffodilDebugger/utils.ts:46]: I will approve this once the formatting CI stage doesn't fail. All you should need to do is run

```bash
yarn lint:fix
git commit -a -m "Fix lint issues"
```

Then squash your commits to a single commit and force push.

If you have not done you will find some instruction below.

## Squash and force push instructions
- Firstly make sure you have the upstream repo origin added to your repo

   ```bash
   git remote add upstream git@github.com:apache/daffodil-vscode.git
   git fetch --all
   ```

   - If you have done this already have this remote then only run `git fetch --all` to make sure you have the latest `main`.

- Rebase your branch off of the `main` branch.

   ```bash
   git rebase -i upstream/main
   ```

   - This will give you a least of commits such as:
      ```txt
      pick 4a7c6b4 changed assigment of extraArgs to be os specific and fix Java 17 on Windows
      pick 5d82c5a Fix lint issues
      ```
   - You will want to change every commit except the first one from `pick` to `s` or `squash`. Then after this it will give you options to update the commit message. Should look like something below:
      ```txt
      # This is a combination of 2 commits.
      # This is the 1st commit message:

      changed assigment of extraArgs to be os specific and fix Java 17 on Windows

      # This is the commit message #2:

      Fix lint issues
      ```
   - In this case you should be able to delete everything other than
      ```txt
      changed assigment of extraArgs to be os specific and fix Java 17 on Windows
      ```
- After the rebase is done you will need to force push to your branch:

   ```bash
   git push --force origin fix-java-17-parameters
   ```

**Comment by scholarsmate** [comment]
Please fix up the commit as @shanedell recommends and I'll approve as well.

**Review by shanedell — APPROVED** [review]

**Review by shanedell — APPROVED** [review]
+1

**Review by scholarsmate — APPROVED** [review]
+1
