### PR TITLE
Fix File/Viewport Navigation Issue

### LINKED ISSUE #819: Small files causing boundary issues in the Data Editor
Scrolling around in a small file caused the following to happen in the UI:

Screenshot 2023-08-17 at 11 13 56 AM

Logs indicate that a negative offset is being sent to the Ωedit server:

```
{"level":"DEBUG","time":"2023-08-17T15:42:51.338Z","pid":86239,"hostname":"evc-1901021","fn":"modifyViewport","rqst":{"viewportId":"L1VzZXJzL3NoZWFyZXJkL0RvY3VtZW50cy9HaXRIdWIvZGFmZm9kaWwtdnNjb2RlLWN0Yy1vc3MvTk9USUNF:caace1e9-95cf-4f3e-ba84-f8c03f8f47c2","offset":-656,"capacity":1024,"isFloating":false}}
```

### PR DESCRIPTION
**Pull request by stricklandrbls**
- Fixes issue where the UI would send viewport data requests w/ invalid offsets if the filesize was less than the viewport capacity.
- Reworked `getLogger` functionality of data editor extension.

Closes #819

### CODE REVIEW

**Review by shanedell — APPROVED** [review]
+1

**Review by rthomas320 — APPROVED** [review]
Pulled a copy and all file sizes worked.

File: src/svelte/src/components/DataDisplays/CustomByteDisplay/DataLineFeed.svelte [hunk 1]
```diff
@@ -65,8 +65,8 @@ limitations under the License.
     updateSearchResultsHighlights,
   } from '../../../utilities/highlights'
 
-  export let lineTop: number
-  export let awaitViewportScroll: boolean
+  // export let $dataFeedLineTop: number
```
Comment (scholarsmate) [inline src/svelte/src/components/DataDisplays/CustomByteDisplay/DataLineFeed.svelte:68]: Remove this line.

**Review by scholarsmate — APPROVED** [review]
+1, 👍 

I pulled this and tested it out.  Seems to work well for tiny, small, medium and large files.  Just remove commented code and get this merged.
